---------------------------------------------
-- Sample Data Generation
---------------------------------------------
USE WAREHOUSE SAP_COMPUTE;



-- Generate 500+ records for each table using Snowflake's generator function

-- MATDOC: 1000 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.S4HANA_ALL_REGIONS.MATDOC
SELECT 
    'MAT' || LPAD(ROW_NUMBER() OVER (ORDER BY SEQ4()), 7, '0') as MBLNR,
    '2024' as MJAHR,
    LPAD(UNIFORM(1, 9999, RANDOM()), 4, '0') as ZEILE,
    'MAT' || LPAD(UNIFORM(1000, 9999, RANDOM()), 14, '0') as MATNR,
    'PL' || LPAD(UNIFORM(1, 99, RANDOM()), 2, '0') as WERKS,
    'SL' || LPAD(UNIFORM(1, 20, RANDOM()), 2, '0') as LAGER,
    'LG' || LPAD(UNIFORM(1, 30, RANDOM()), 2, '0') as LGORT,
    CASE UNIFORM(1, 10, RANDOM())
        WHEN 1 THEN '101' WHEN 2 THEN '102' WHEN 3 THEN '201' 
        WHEN 4 THEN '202' WHEN 5 THEN '301' WHEN 6 THEN '302'
        ELSE '501' END as BWART,
    DATEADD(day, -UNIFORM(0, 365, RANDOM()), CURRENT_DATE) as BUDAT,
    DATEADD(day, -UNIFORM(0, 365, RANDOM()), CURRENT_DATE) as CPUDT,
    TIMEADD(second, UNIFORM(0, 86400, RANDOM()), '00:00:00'::TIME) as CPUTM,
    'USER' || LPAD(UNIFORM(1, 50, RANDOM()), 3, '0') as USNAM,
    UNIFORM(10, 10000, RANDOM()) * 1.0 as MENGE,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN 'EA' WHEN 2 THEN 'KG' ELSE 'L' END as MEINS,
    UNIFORM(100, 50000, RANDOM()) * 1.0 as DMBTR,
    'USD' as WAERS,
    'VEN' || LPAD(UNIFORM(1, 100, RANDOM()), 7, '0') as LIFNR,
    'CUS' || LPAD(UNIFORM(1, 200, RANDOM()), 7, '0') as KUNNR,
    'ORD' || LPAD(UNIFORM(1, 500, RANDOM()), 9, '0') as AUFNR,
    'SO' || LPAD(UNIFORM(1, 1000, RANDOM()), 8, '0') as KDAUF,
    LPAD(UNIFORM(1, 99, RANDOM()), 2, '0') as KDPOS,
    'REF' || LPAD(UNIFORM(1, 9999, RANDOM()), 12, '0') as XBLNR,
    'Text ' || UNIFORM(1, 100, RANDOM()) as BKTXT,
    CASE UNIFORM(1, 5, RANDOM()) WHEN 1 THEN 'WE' WHEN 2 THEN 'WA' ELSE 'RE' END as BLART,
    DATEADD(day, -UNIFORM(0, 30, RANDOM()), BUDAT) as BLDAT,
    'BATCH' || LPAD(UNIFORM(1, 500, RANDOM()), 5, '0') as CHARG,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN 'S' ELSE '' END as SOBKZ,
    MENGE * UNIFORM(0.9, 1.1, RANDOM()) as ERFMG,
    MEINS as ERFME,
    CASE UNIFORM(1, 2, RANDOM()) WHEN 1 THEN 'S' ELSE 'H' END as SHKZG
FROM TABLE(GENERATOR(ROWCOUNT => 1000));

-- ME2N: 500 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.S4HANA_ALL_REGIONS.ME2N
SELECT 
    'PO' || LPAD(ROW_NUMBER() OVER (ORDER BY SEQ4()), 8, '0') as EBELN,
    LPAD(UNIFORM(1, 99, RANDOM()), 2, '0') as EBELP,
    'VEN' || LPAD(UNIFORM(1, 100, RANDOM()), 7, '0') as LIFNR,
    'Supplier ' || UNIFORM(1, 100, RANDOM()) as NAME1,
    'PUR' || LPAD(UNIFORM(1, 10, RANDOM()), 1, '0') as EKORG,
    'G' || LPAD(UNIFORM(1, 20, RANDOM()), 2, '0') as EKGRP,
    'MAT' || LPAD(UNIFORM(1000, 9999, RANDOM()), 14, '0') as MATNR,
    'Material Description ' || UNIFORM(1, 500, RANDOM()) as TXZ01,
    'PL' || LPAD(UNIFORM(1, 99, RANDOM()), 2, '0') as WERKS,
    'LG' || LPAD(UNIFORM(1, 30, RANDOM()), 2, '0') as LGORT,
    UNIFORM(10, 1000, RANDOM()) * 1.0 as MENGE,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN 'EA' WHEN 2 THEN 'KG' ELSE 'L' END as MEINS,
    MENGE as BSTMG,
    MENGE * UNIFORM(0, 100, RANDOM()) / 100.0 as WEMNG,
    MENGE - WEMNG as REMNG,
    DATEADD(day, -UNIFORM(0, 90, RANDOM()), CURRENT_DATE) as BEDAT,
    DATEADD(day, UNIFORM(1, 60, RANDOM()), BEDAT) as EINDT,
    CASE UNIFORM(1, 4, RANDOM()) WHEN 1 THEN 'N' WHEN 2 THEN 'U' WHEN 3 THEN 'L' ELSE 'F' END as BSTYP,
    CASE UNIFORM(1, 4, RANDOM()) WHEN 1 THEN 'N' WHEN 2 THEN 'U' ELSE 'F' END as BSART,
    UNIFORM(10, 500, RANDOM()) * 1.0 as NETPR,
    UNIFORM(1, 10, RANDOM()) as PEINH,
    'USD' as WAERS,
    NETPR * MENGE as BRTWR,
    '00' as LPEIN,
    LPAD(UNIFORM(1, 12, RANDOM()), 2, '0') as LFMON,
    '' as VRTKZ,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN '01' WHEN 2 THEN '02' ELSE '03' END as VERSART,
    CASE WHEN REMNG = 0 THEN 'L' ELSE '' END as LOEKZ,
    CASE WHEN WEMNG > 0 THEN 'C' ELSE 'O' END as STATU,
    '' as MEMORY
FROM TABLE(GENERATOR(ROWCOUNT => 500));

-- MARC: 500 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.S4HANA_ALL_REGIONS.MARC
SELECT 
    '100' as MANDT,
    'MAT' || LPAD(UNIFORM(1000, 9999, RANDOM()), 14, '0') as MATNR,
    'PL' || LPAD(UNIFORM(1, 99, RANDOM()), 2, '0') as WERKS,
    'D' || LPAD(UNIFORM(1, 20, RANDOM()), 2, '0') as DISPO,
    CASE UNIFORM(1, 5, RANDOM()) 
        WHEN 1 THEN 'PD' WHEN 2 THEN 'VB' 
        WHEN 3 THEN 'ND' WHEN 4 THEN 'VV' 
        ELSE 'VM' END as DISMM,
    'D' || LPAD(UNIFORM(1, 20, RANDOM()), 2, '0') as DISPO_OLD,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN 'E' WHEN 2 THEN 'F' ELSE 'X' END as BESKZ,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN '10' WHEN 2 THEN '20' ELSE '30' END as SOBSL,
    UNIFORM(10, 500, RANDOM()) * 1.0 as MINBE,
    UNIFORM(5, 250, RANDOM()) * 1.0 as EISBE,
    UNIFORM(10, 100, RANDOM()) * 1.0 as BSTMI,
    UNIFORM(500, 5000, RANDOM()) * 1.0 as BSTMA,
    UNIFORM(50, 200, RANDOM()) * 1.0 as BSTFE,
    UNIFORM(1, 30, RANDOM()) as PLIFZ,
    UNIFORM(0, 5, RANDOM()) as WEBAZ,
    UNIFORM(0, 3, RANDOM()) as BEARZ,
    UNIFORM(0, 2, RANDOM()) as RUEZT,
    UNIFORM(0, 7, RANDOM()) as TRANSZ,
    CASE UNIFORM(1, 4, RANDOM()) 
        WHEN 1 THEN 'EX' WHEN 2 THEN 'WK' 
        WHEN 3 THEN 'MO' ELSE 'TB' END as LOSGR,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN 'W' WHEN 2 THEN 'M' ELSE 'P' END as PERKZ,
    'K4' as PERIV,
    '1' as AUSSS,
    '1' as KZPRD,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN '1' WHEN 2 THEN '2' ELSE '3' END as VRMOD,
    '1' as VINT1,
    '2' as VINT2,
    '01' as FHORI,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 80 THEN 'X' ELSE '' END as WEBRE,
    LPAD(UNIFORM(1, 9, RANDOM()), 1, '0') as PRCTL,
    'LG' || LPAD(UNIFORM(1, 10, RANDOM()), 2, '0') as LGPRO,
    UNIFORM(50, 100, RANDOM()) / 100.0 as LGRAD,
    'D' || LPAD(UNIFORM(1, 5, RANDOM()), 3, '0') as DISPR
FROM TABLE(GENERATOR(ROWCOUNT => 500));

-- MD04: 750 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.S4HANA_ALL_REGIONS.MD04
SELECT 
    '100' as MANDT,
    'MAT' || LPAD(UNIFORM(1000, 9999, RANDOM()), 14, '0') as MATNR,
    'PL' || LPAD(UNIFORM(1, 99, RANDOM()), 2, '0') as WERKS,
    'MRP' || LPAD(UNIFORM(1, 20, RANDOM()), 4, '0') as BERID,
    CASE UNIFORM(1, 6, RANDOM()) 
        WHEN 1 THEN 'CU' WHEN 2 THEN 'DL' 
        WHEN 3 THEN 'PE' WHEN 4 THEN 'PR'
        WHEN 5 THEN 'RE' ELSE 'SA' END as DTART,
    DATEADD(day, UNIFORM(-30, 90, RANDOM()), CURRENT_DATE) as DTERQ,
    'PL' || LPAD(UNIFORM(1000, 9999, RANDOM()), 6, '0') as PLNUM,
    'PO' || LPAD(UNIFORM(1000, 9999, RANDOM()), 6, '0') as PLORD,
    'RS' || LPAD(UNIFORM(1000, 9999, RANDOM()), 6, '0') as RESB,
    UNIFORM(50, 5000, RANDOM()) * 1.0 as MENGE,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN 'EA' WHEN 2 THEN 'KG' ELSE 'L' END as MEINS,
    MENGE * UNIFORM(0, 100, RANDOM()) / 100.0 as ENMNG,
    MENGE - ENMNG as OPNG,
    UNIFORM(100, 10000, RANDOM()) * 1.0 as LABST,
    UNIFORM(0, 1000, RANDOM()) * 1.0 as UMLMC,
    UNIFORM(0, 500, RANDOM()) * 1.0 as INSME,
    UNIFORM(0, 2000, RANDOM()) * 1.0 as EINME,
    'D' || LPAD(UNIFORM(1, 20, RANDOM()), 2, '0') as DISPO,
    CASE UNIFORM(1, 4, RANDOM()) 
        WHEN 1 THEN 'EX' WHEN 2 THEN 'WK' 
        WHEN 3 THEN 'MO' ELSE 'TB' END as DISLS,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN 'E' WHEN 2 THEN 'F' ELSE 'X' END as BESKZ,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN '10' WHEN 2 THEN '20' ELSE '30' END as SOBSL,
    UNIFORM(1, 10, RANDOM()) as WZEIT,
    UNIFORM(1, 30, RANDOM()) as PLIFZ,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 90 THEN 'X' ELSE '' END as WEBRE,
    'VEN' || LPAD(UNIFORM(1, 100, RANDOM()), 7, '0') as LIFNR,
    'G' || LPAD(UNIFORM(1, 20, RANDOM()), 2, '0') as EKGRP,
    CASE DTART 
        WHEN 'CU' THEN 'C' 
        WHEN 'DL' THEN 'D'
        WHEN 'PE' THEN 'P'
        ELSE 'S' END as DELKZ,
    '' as DELET
FROM TABLE(GENERATOR(ROWCOUNT => 750));

-- S4HANA_APAC Tables
-- VBAK: 600 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.S4HANA_APAC.VBAK
SELECT 
    'SO' || LPAD(ROW_NUMBER() OVER (ORDER BY SEQ4()), 8, '0') as VBELN,
    DATEADD(day, -UNIFORM(0, 365, RANDOM()), CURRENT_DATE) as ERDAT,
    TIMEADD(second, UNIFORM(0, 86400, RANDOM()), '00:00:00'::TIME) as ERZET,
    'USER' || LPAD(UNIFORM(1, 50, RANDOM()), 3, '0') as ERNAM,
    'CUS' || LPAD(UNIFORM(1, 200, RANDOM()), 7, '0') as KUNNR,
    'CUS' || LPAD(UNIFORM(1, 200, RANDOM()), 7, '0') as KUNAG,
    'CUS' || LPAD(UNIFORM(1, 200, RANDOM()), 7, '0') as KUNRE,
    'CUS' || LPAD(UNIFORM(1, 200, RANDOM()), 7, '0') as KUNWE,
    CASE UNIFORM(1, 4, RANDOM()) 
        WHEN 1 THEN 'OR' WHEN 2 THEN 'QU' 
        WHEN 3 THEN 'RE' ELSE 'SO' END as AUART,
    'AP' || LPAD(UNIFORM(1, 5, RANDOM()), 2, '0') as VKORG,
    LPAD(UNIFORM(1, 3, RANDOM()), 2, '0') as VTWEG,
    LPAD(UNIFORM(1, 5, RANDOM()), 2, '0') as SPART,
    ERDAT as AUDAT,
    DATEADD(day, UNIFORM(1, 30, RANDOM()), ERDAT) as VDATU,
    DATEADD(day, UNIFORM(5, 35, RANDOM()), ERDAT) as WADAT,
    DATEADD(day, -UNIFORM(0, 7, RANDOM()), ERDAT) as BSTDK,
    'PO-' || LPAD(UNIFORM(1000, 9999, RANDOM()), 8, '0') as BSTZD,
    UNIFORM(1000, 100000, RANDOM()) * 1.0 as NETWR,
    'USD' as WAERK,
    'O' || LPAD(UNIFORM(1, 10, RANDOM()), 3, '0') as VKBUR,
    'G' || LPAD(UNIFORM(1, 10, RANDOM()), 2, '0') as VKGRP,
    'PR00' as KALSM,
    ERDAT as PRSDT,
    'PROMO' || LPAD(UNIFORM(1, 20, RANDOM()), 5, '0') as KNUMA,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 95 THEN 'C' ELSE 'B' END as GBSTK,
    CASE WHEN WADAT > CURRENT_DATE THEN 'A' ELSE 'C' END as FKSTK,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 5 THEN '1' ELSE '' END as LIFSK,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 3 THEN '1' ELSE '' END as FAKSK,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN '01' WHEN 2 THEN '02' ELSE '03' END as VSBED,
    LPAD(UNIFORM(1, 5, RANDOM()), 1, '0') as LPRIO,
    'R' || LPAD(UNIFORM(1, 20, RANDOM()), 3, '0') as ROUTE
FROM TABLE(GENERATOR(ROWCOUNT => 600));

-- VBAP: 1200 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.S4HANA_APAC.VBAP
SELECT 
    'SO' || LPAD(UNIFORM(1, 600, RANDOM()), 8, '0') as VBELN,
    LPAD(UNIFORM(1, 10, RANDOM()), 6, '0') as POSNR,
    'MAT' || LPAD(UNIFORM(1000, 9999, RANDOM()), 14, '0') as MATNR,
    'Product Description ' || UNIFORM(1, 500, RANDOM()) as ARKTX,
    'PL' || LPAD(UNIFORM(1, 99, RANDOM()), 2, '0') as WERKS,
    'LG' || LPAD(UNIFORM(1, 30, RANDOM()), 2, '0') as LGORT,
    'BATCH' || LPAD(UNIFORM(1, 500, RANDOM()), 5, '0') as CHARG,
    UNIFORM(10, 500, RANDOM()) * 1.0 as KWMENG,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN 'EA' WHEN 2 THEN 'KG' ELSE 'L' END as VRKME,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN 'EA' WHEN 2 THEN 'KG' ELSE 'L' END as MEINS,
    UNIFORM(1, 10, RANDOM()) as UMZIN,
    1 as UMZIZ,
    UNIFORM(50, 5000, RANDOM()) * 1.0 as NETWR,
    UNIFORM(10, 100, RANDOM()) * 1.0 as NETPR,
    UNIFORM(1, 10, RANDOM()) as PEINH,
    UNIFORM(1, 10, RANDOM()) as KPEIN,
    LPAD(UNIFORM(1, 3, RANDOM()), 1, '0') as EDTNR,
    DATEADD(day, UNIFORM(5, 30, RANDOM()), CURRENT_DATE) as EINDT,
    LPAD(UNIFORM(1, 3, RANDOM()), 1, '0') as ETENR,
    CASE UNIFORM(1, 4, RANDOM()) 
        WHEN 1 THEN 'TAN' WHEN 2 THEN 'TAS' 
        WHEN 3 THEN 'TAD' ELSE 'TAB' END as PSTYV,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 2 THEN '01' ELSE '' END as ABGRU,
    CASE WHEN DATEADD(day, UNIFORM(5, 30, RANDOM()), CURRENT_DATE) < CURRENT_DATE THEN 'C' ELSE 'A' END as LFSTA,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 90 THEN 'A' ELSE 'B' END as FKSTA,
    'CONF' || LPAD(UNIFORM(1, 1000, RANDOM()), 12, '0') as CUOBJ,
    LPAD(UNIFORM(1, 99, RANDOM()), 3, '0') as POSEX
FROM TABLE(GENERATOR(ROWCOUNT => 1200));

-- LIKP: 500 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.S4HANA_APAC.LIKP
SELECT 
    'DL' || LPAD(ROW_NUMBER() OVER (ORDER BY SEQ4()), 8, '0') as VBELN,
    DATEADD(day, -UNIFORM(0, 30, RANDOM()), CURRENT_DATE) as ERDAT,
    TIMEADD(second, UNIFORM(0, 86400, RANDOM()), '00:00:00'::TIME) as ERZET,
    'USER' || LPAD(UNIFORM(1, 50, RANDOM()), 3, '0') as ERNAM,
    CASE UNIFORM(1, 3, RANDOM()) 
        WHEN 1 THEN 'LF' WHEN 2 THEN 'LP' ELSE 'LR' END as LFART,
    'AP' || LPAD(UNIFORM(1, 5, RANDOM()), 2, '0') as VKORG,
    LPAD(UNIFORM(1, 3, RANDOM()), 2, '0') as VTWEG,
    LPAD(UNIFORM(1, 5, RANDOM()), 2, '0') as SPART,
    'CUS' || LPAD(UNIFORM(1, 200, RANDOM()), 7, '0') as KUNNR,
    'CUS' || LPAD(UNIFORM(1, 200, RANDOM()), 7, '0') as KUNAG,
    'VEN' || LPAD(UNIFORM(1, 100, RANDOM()), 7, '0') as LIFNR,
    'AD' || LPAD(UNIFORM(1, 500, RANDOM()), 8, '0') as ADRNR,
    DATEADD(day, UNIFORM(-2, 5, RANDOM()), CURRENT_DATE) as WADAT,
    DATEADD(day, -UNIFORM(0, 2, RANDOM()), WADAT) as LDDAT,
    DATEADD(day, -UNIFORM(0, 3, RANDOM()), WADAT) as TDDAT,
    DATEADD(day, -UNIFORM(0, 1, RANDOM()), WADAT) as LFDAT,
    'R' || LPAD(UNIFORM(1, 20, RANDOM()), 3, '0') as ROUTE,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN '01' WHEN 2 THEN '02' ELSE '03' END as VSBED,
    LPAD(UNIFORM(1, 5, RANDOM()), 1, '0') as LPRIO,
    'TR' || LPAD(UNIFORM(1, 10, RANDOM()), 2, '0') as TRAGR,
    CASE WHEN WADAT <= CURRENT_DATE THEN 'C' ELSE 'A' END as WBSTK,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 80 THEN 'C' ELSE 'A' END as FKSTK,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 90 THEN 'C' ELSE 'A' END as KODAT,
    VKORG as VKORG_DEL,
    UNIFORM(100, 5000, RANDOM()) * 1.0 as BRGEW,
    BRGEW * UNIFORM(0.7, 0.9, RANDOM()) as NTGEW,
    'KG' as GEWEI,
    UNIFORM(1, 100, RANDOM()) * 1.0 as VOLUM,
    'M3' as VOLEH
FROM TABLE(GENERATOR(ROWCOUNT => 500));

-- LIPS: 1500 records (multiple items per delivery)
INSERT INTO SAP_BDC_HORIZON_CATALOG.S4HANA_APAC.LIPS
SELECT 
    'DL' || LPAD(UNIFORM(1, 500, RANDOM()), 8, '0') as VBELN,
    LPAD(UNIFORM(1, 10, RANDOM()), 6, '0') as POSNR,
    'MAT' || LPAD(UNIFORM(1000, 9999, RANDOM()), 14, '0') as MATNR,
    'Product Description ' || UNIFORM(1, 500, RANDOM()) as ARKTX,
    'PL' || LPAD(UNIFORM(1, 99, RANDOM()), 2, '0') as WERKS,
    'LG' || LPAD(UNIFORM(1, 30, RANDOM()), 2, '0') as LGORT,
    'BATCH' || LPAD(UNIFORM(1, 500, RANDOM()), 5, '0') as CHARG,
    UNIFORM(10, 500, RANDOM()) * 1.0 as LFIMG,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN 'EA' WHEN 2 THEN 'KG' ELSE 'L' END as MEINS,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN 'EA' WHEN 2 THEN 'KG' ELSE 'L' END as VRKME,
    UNIFORM(1, 10, RANDOM()) as UMZIN,
    1 as UMZIZ,
    'SO' || LPAD(UNIFORM(1, 600, RANDOM()), 8, '0') as VGBEL,
    LPAD(UNIFORM(1, 10, RANDOM()), 3, '0') as VGPOS,
    'V' as VGTYP,
    'SO' || LPAD(UNIFORM(1, 600, RANDOM()), 8, '0') as AUBEL,
    LPAD(UNIFORM(1, 10, RANDOM()), 3, '0') as AUPOS,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 95 THEN 'C' ELSE 'A' END as PKSTK,
    LFIMG * UNIFORM(0, 100, RANDOM()) / 100.0 as PIKMG,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 90 THEN 'X' ELSE '' END as KOMKZ,
    'G' || LPAD(UNIFORM(1, 10, RANDOM()), 2, '0') as GRKOR,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 70 THEN 'C' ELSE 'A' END as LFSTA,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 80 THEN 'C' ELSE 'A' END as WBSTA,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 80 THEN 'C' ELSE 'A' END as FKSTA,
    '' as LVSBL,
    UNIFORM(100, 5000, RANDOM()) * 1.0 as NETWR,
    UNIFORM(10, 100, RANDOM()) * 1.0 as NETPR,
    UNIFORM(1, 10, RANDOM()) as PEINH
FROM TABLE(GENERATOR(ROWCOUNT => 1500));

-- KONV: 2000 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.S4HANA_APAC.KONV
SELECT 
    'KN' || LPAD(UNIFORM(1, 600, RANDOM()), 8, '0') as KNUMV,
    LPAD(UNIFORM(1, 10, RANDOM()), 3, '0') as KPOSN,
    LPAD(UNIFORM(1, 5, RANDOM()), 2, '0') as STUNR,
    LPAD(UNIFORM(1, 3, RANDOM()), 2, '0') as ZAEHK,
    CASE UNIFORM(1, 10, RANDOM())
        WHEN 1 THEN 'PR00' WHEN 2 THEN 'K004' WHEN 3 THEN 'K005'
        WHEN 4 THEN 'K007' WHEN 5 THEN 'KA00' WHEN 6 THEN 'K029'
        ELSE 'PR01' END as KSCHL,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN 'V' WHEN 2 THEN 'M' ELSE 'A' END as KAPPL,
    LPAD(UNIFORM(1, 999, RANDOM()), 3, '0') as KOTABNR,
    CASE KSCHL
        WHEN 'PR00' THEN UNIFORM(10, 100, RANDOM()) * 1.0
        WHEN 'K004' THEN UNIFORM(1, 15, RANDOM()) * 1.0
        WHEN 'K005' THEN UNIFORM(2, 10, RANDOM()) * 1.0
        ELSE UNIFORM(0, 20, RANDOM()) * 1.0
    END as KBETR,
    '%' as KOEIN,
    UNIFORM(1, 10, RANDOM()) as KPEIN,
    UNIFORM(1, 100, RANDOM()) as KUMZA,
    100 as KUMNE,
    'USD' as WAERS,
    CASE WHEN KAPPL = 'V' THEN 'A' ELSE 'B' END as KNTYP,
    UNIFORM(100, 10000, RANDOM()) * 1.0 as KSTBS,
    CASE UNIFORM(1, 4, RANDOM()) 
        WHEN 1 THEN 'A' WHEN 2 THEN 'B' 
        WHEN 3 THEN 'C' ELSE 'D' END as KRECH,
    '' as KOUPD,
    DATEADD(day, -UNIFORM(0, 90, RANDOM()), CURRENT_DATE) as DATVO,
    DATEADD(day, UNIFORM(30, 365, RANDOM()), DATVO) as DATBI,
    '' as KOBLI,
    'PROMO' || LPAD(UNIFORM(1, 20, RANDOM()), 5, '0') as KNUMA,
    CASE KAPPL WHEN 'V' THEN 'A' ELSE 'B' END as KVEWE,
    'Condition Text ' || UNIFORM(1, 100, RANDOM()) as KOTEXT
FROM TABLE(GENERATOR(ROWCOUNT => 2000));

-- S4HANA_EMEA Tables

-- ACDOCA: 2000 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.S4HANA_EMEA.ACDOCA
SELECT 
    '100' as RCLNT,
    'EM' || LPAD(UNIFORM(1, 10, RANDOM()), 2, '0') as RBUKRS,
    '2024' as GJAHR,
    'DOC' || LPAD(ROW_NUMBER() OVER (ORDER BY SEQ4()), 7, '0') as BELNR,
    LPAD(UNIFORM(1, 999, RANDOM()), 3, '0') as DOCLN,
    CASE UNIFORM(1, 5, RANDOM()) 
        WHEN 1 THEN 'SA' WHEN 2 THEN 'RE' 
        WHEN 3 THEN 'KR' WHEN 4 THEN 'KG' ELSE 'RV' END as BLART,
    DATEADD(day, -UNIFORM(0, 90, RANDOM()), CURRENT_DATE) as BLDAT,
    DATEADD(day, -UNIFORM(0, 30, RANDOM()), BLDAT) as BUDAT,
    BLDAT as CPUDT,
    TIMEADD(second, UNIFORM(0, 86400, RANDOM()), '00:00:00'::TIME) as CPUTM,
    'USER' || LPAD(UNIFORM(1, 50, RANDOM()), 3, '0') as USNAM,
    CASE UNIFORM(1, 5, RANDOM()) 
        WHEN 1 THEN 'RV' WHEN 2 THEN 'RE' 
        WHEN 3 THEN 'SD' ELSE 'FB' END as AWTYP,
    BELNR as AWKEY,
    'ACC' || LPAD(UNIFORM(1000, 9999, RANDOM()), 6, '0') as RACCT,
    'CC' || LPAD(UNIFORM(1, 100, RANDOM()), 5, '0') as RCNTR,
    'PC' || LPAD(UNIFORM(1, 50, RANDOM()), 5, '0') as PRCTR,
    'SEG' || LPAD(UNIFORM(1, 20, RANDOM()), 3, '0') as SEGMENT,
    UNIFORM(-50000, 100000, RANDOM()) * 1.0 as HSL,
    HSL * UNIFORM(0.8, 1.2, RANDOM()) as TSL,
    HSL as MSL,
    HSL as KSL,
    'EUR' as RWCUR,
    UNIFORM(1, 1000, RANDOM()) * 1.0 as MENGE,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN 'EA' WHEN 2 THEN 'KG' ELSE 'L' END as MEINS,
    'User ' || UNIFORM(1, 50, RANDOM()) as ERNAME,
    'CA' || LPAD(UNIFORM(1, 10, RANDOM()), 2, '0') as KOKRS,
    RCNTR as KOSTL,
    'ORD' || LPAD(UNIFORM(1, 500, RANDOM()), 9, '0') as AUFNR,
    'SO' || LPAD(UNIFORM(1, 600, RANDOM()), 8, '0') as VBELN,
    LPAD(UNIFORM(1, 10, RANDOM()), 3, '0') as POSNR,
    'MAT' || LPAD(UNIFORM(1000, 9999, RANDOM()), 14, '0') as MATNR,
    'PL' || LPAD(UNIFORM(1, 99, RANDOM()), 2, '0') as WERKS,
    'CUS' || LPAD(UNIFORM(1, 200, RANDOM()), 7, '0') as KUNNR,
    'VEN' || LPAD(UNIFORM(1, 100, RANDOM()), 7, '0') as LIFNR,
    'PA' || LPAD(UNIFORM(1, 1000, RANDOM()), 8, '0') as PAOBJNR,
    PRCTR as PRCTR_UP,
    PRCTR as PPRCTR,
    CASE WHEN RACCT LIKE '1%' THEN 'X' ELSE '' END as XBILK,
    '' as XSPLITMOD,
    '' as STBLG,
    '' as STJAH
FROM TABLE(GENERATOR(ROWCOUNT => 2000));

-- FAGLFLEXA: 1500 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.S4HANA_EMEA.FAGLFLEXA
SELECT 
    '100' as RCLNT,
    'EM' || LPAD(UNIFORM(1, 10, RANDOM()), 2, '0') as RBUKRS,
    '0L' as RLDNR,
    '2024' as GJAHR,
    'DOC' || LPAD(UNIFORM(1, 2000, RANDOM()), 7, '0') as BELNR,
    LPAD(UNIFORM(1, 999, RANDOM()), 3, '0') as DOCLN,
    'ACC' || LPAD(UNIFORM(1000, 9999, RANDOM()), 6, '0') as RACCT,
    'CC' || LPAD(UNIFORM(1, 100, RANDOM()), 5, '0') as RCNTR,
    'PC' || LPAD(UNIFORM(1, 50, RANDOM()), 5, '0') as PRCTR,
    'FA' || LPAD(UNIFORM(1, 10, RANDOM()), 3, '0') as RFAREA,
    'SEG' || LPAD(UNIFORM(1, 20, RANDOM()), 3, '0') as SEGMENT,
    UNIFORM(-50000, 100000, RANDOM()) * 1.0 as HSL01,
    HSL01 * UNIFORM(0.9, 1.1, RANDOM()) as HSL02,
    HSL01 * UNIFORM(0.95, 1.05, RANDOM()) as HSL03,
    'EUR' as RWCUR1,
    'USD' as RWCUR2,
    'GBP' as RWCUR3,
    DATEADD(day, -UNIFORM(0, 90, RANDOM()), CURRENT_DATE) as BUDAT,
    DATEADD(day, -UNIFORM(0, 7, RANDOM()), BUDAT) as BLDAT,
    LPAD(UNIFORM(1, 12, RANDOM()), 2, '0') as PERID,
    GJAHR || PERID as FISCYEARPER,
    'CA' || LPAD(UNIFORM(1, 10, RANDOM()), 2, '0') as KOKRS,
    RCNTR as KOSTL,
    'ORD' || LPAD(UNIFORM(1, 500, RANDOM()), 9, '0') as AUFNR,
    'SO' || LPAD(UNIFORM(1, 600, RANDOM()), 8, '0') as VBELN,
    LPAD(UNIFORM(1, 10, RANDOM()), 3, '0') as POSNR,
    'MAT' || LPAD(UNIFORM(1000, 9999, RANDOM()), 14, '0') as MATNR,
    'PL' || LPAD(UNIFORM(1, 99, RANDOM()), 2, '0') as WERKS,
    'CUS' || LPAD(UNIFORM(1, 200, RANDOM()), 7, '0') as KUNNR,
    'VEN' || LPAD(UNIFORM(1, 100, RANDOM()), 7, '0') as LIFNR,
    'REF' || LPAD(UNIFORM(1, 9999, RANDOM()), 12, '0') as XBLNR,
    CASE UNIFORM(1, 5, RANDOM()) 
        WHEN 1 THEN 'SA' WHEN 2 THEN 'RE' 
        WHEN 3 THEN 'KR' WHEN 4 THEN 'KG' ELSE 'RV' END as BLART,
    '' as BSTAT,
    '' as XREVERSING,
    '' as STBLG
FROM TABLE(GENERATOR(ROWCOUNT => 1500));

-- ECC_AMERICAS Tables

-- PA0007: 800 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.ECC_AMERICAS.PA0007
SELECT 
    LPAD(ROW_NUMBER() OVER (ORDER BY SEQ4()), 6, '0') as PERNR,
    '0' as SUBTY,
    '00' as OBJPS,
    ' ' as SPRPS,
    DATEADD(day, UNIFORM(30, 730, RANDOM()), CURRENT_DATE) as ENDDA,
    DATEADD(day, -UNIFORM(0, 365, RANDOM()), CURRENT_DATE) as BEGDA,
    '001' as SEQNR,
    CASE UNIFORM(1, 5, RANDOM())
        WHEN 1 THEN 'S1' WHEN 2 THEN 'S2' 
        WHEN 3 THEN 'F1' WHEN 4 THEN 'F2' ELSE 'R1' END as SCHKZ,
    LPAD(UNIFORM(1, 9, RANDOM()), 1, '0') as ZTERF,
    'W' || LPAD(UNIFORM(1, 10, RANDOM()), 2, '0') as TPROG,
    'D' || LPAD(UNIFORM(1, 5, RANDOM()), 1, '0') as TPLAN,
    LPAD(UNIFORM(1, 999, RANDOM()), 3, '0') as VARIA,
    CASE SCHKZ
        WHEN 'S1' THEN 40.0
        WHEN 'S2' THEN 35.0
        WHEN 'F1' THEN 20.0
        WHEN 'F2' THEN 25.0
        ELSE 37.5
    END as STDVL,
    STDVL * 4.33 as STDVA,
    STDVL / 5 as STDVP,
    STDVP as STDTA,
    CASE WHEN SCHKZ LIKE 'S%' THEN 8.0 ELSE 0 END as STDFR,
    CASE WHEN SCHKZ LIKE 'S%' THEN 0 ELSE 8 END as STDSA,
    0 as STDSU,
    STDVP as STDMO,
    STDVP as STDTU,
    STDVP as STDWE,
    STDVP as STDTH,
    CASE UNIFORM(1, 4, RANDOM()) 
        WHEN 1 THEN 'M1' WHEN 2 THEN 'M2' 
        WHEN 3 THEN 'E1' ELSE 'N1' END as SHKZG,
    CASE SHKZG WHEN 'N1' THEN 'N' ELSE 'S' END as SPKZL,
    CASE WHEN SCHKZ LIKE 'S%' THEN 5 ELSE 7 END as SCHED_DAYS,
    SCHED_DAYS as WORKDAYS,
    'T' || LPAD(UNIFORM(1, 5, RANDOM()), 2, '0') as ZMODN,
    'TM' || LPAD(UNIFORM(1, 3, RANDOM()), 1, '0') as ZMODE,
    'X' as DYMOD,
    LPAD(UNIFORM(1, 52, RANDOM()), 2, '0') as ZWEEK,
    LPAD(UNIFORM(1, 12, RANDOM()), 2, '0') as ZMONTH,
    STDVA * 4 as CAPACITY_HRS,
    UNIFORM(60, 100, RANDOM()) as UTILIZATION_RATE,
    'A' as AVAILABILITY
FROM TABLE(GENERATOR(ROWCOUNT => 800));

-- PA0008: 800 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.ECC_AMERICAS.PA0008
SELECT 
    PERNR,
    '0' as SUBTY,
    '00' as OBJPS,
    ' ' as SPRPS,
    ENDDA,
    BEGDA,
    '001' as SEQNR,
    CASE UNIFORM(1, 5, RANDOM())
        WHEN 1 THEN 'TA' WHEN 2 THEN 'TB' 
        WHEN 3 THEN 'GA' WHEN 4 THEN 'GB' ELSE 'MA' END as TRFAR,
    CASE TRFAR
        WHEN 'TA' THEN 'E' || LPAD(UNIFORM(1, 5, RANDOM()), 1, '0')
        WHEN 'TB' THEN 'M' || LPAD(UNIFORM(1, 5, RANDOM()), 1, '0')
        ELSE 'A' || LPAD(UNIFORM(1, 5, RANDOM()), 1, '0')
    END as TRFGB,
    LPAD(UNIFORM(1, 12, RANDOM()), 2, '0') as TRFGR,
    LPAD(UNIFORM(1, 6, RANDOM()), 2, '0') as TRFST,
    '' as TRFKZ,
    CASE TRFGR
        WHEN '01' THEN UNIFORM(40000, 60000, RANDOM())
        WHEN '02' THEN UNIFORM(45000, 70000, RANDOM())
        WHEN '03' THEN UNIFORM(50000, 80000, RANDOM())
        WHEN '04' THEN UNIFORM(60000, 90000, RANDOM())
        WHEN '05' THEN UNIFORM(65000, 95000, RANDOM())
        WHEN '06' THEN UNIFORM(70000, 100000, RANDOM())
        WHEN '07' THEN UNIFORM(75000, 110000, RANDOM())
        WHEN '08' THEN UNIFORM(80000, 120000, RANDOM())
        WHEN '09' THEN UNIFORM(85000, 130000, RANDOM())
        WHEN '10' THEN UNIFORM(90000, 140000, RANDOM())
        WHEN '11' THEN UNIFORM(95000, 150000, RANDOM())
        ELSE UNIFORM(100000, 200000, RANDOM())
    END as BETRG,
    'USD' as WAERS,
    1.0 as ANZHL,
    'Salary ' || TRFGR as EITXT,
    'YR' as ZEINH,
    '1' as PERIO,
    'M' as ZFPER,
    'Regular Pay' as ZWECK,
    CASE WHEN SCHKZ LIKE 'F%' THEN 50 ELSE 100 END as EMPCT,
    'JOB' || LPAD(UNIFORM(1, 50, RANDOM()), 3, '0') as JOBID,
    'CC' || LPAD(UNIFORM(1, 100, RANDOM()), 5, '0') as COSTCENTER,
    BETRG * 0.1 as BONUS_AMOUNT,
    10.0 as BONUS_PERCENT,
    CASE WHEN SCHKZ LIKE 'S%' THEN 1.5 ELSE 1.0 END as OVERTIME_RATE,
    CASE SHKZG 
        WHEN 'M1' THEN 5000
        WHEN 'M2' THEN 3000
        WHEN 'E1' THEN 2000
        ELSE 0
    END as SHIFT_DIFF,
    BETRG / 2080 as HOURLY_COST,
    BETRG / 12 as MONTHLY_COST,
    BETRG as ANNUAL_COST
FROM SAP_BDC_HORIZON_CATALOG.ECC_AMERICAS.PA0007
LIMIT 800;

-- PP01: 400 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.ECC_AMERICAS.PP01
SELECT 
    CASE UNIFORM(1, 3, RANDOM()) 
        WHEN 1 THEN 'W' WHEN 2 THEN 'M' ELSE 'P' END as OTYPE,
    'WC' || LPAD(ROW_NUMBER() OVER (ORDER BY SEQ4()), 6, '0') as OBJID,
    '01' as PLVAR,
    DATEADD(day, -UNIFORM(0, 365, RANDOM()), CURRENT_DATE) as BEGDA,
    DATEADD(day, UNIFORM(365, 1095, RANDOM()), BEGDA) as ENDDA,
    '1' as ISTAT,
    '' as HISTO,
    LEFT(OBJID, 8) as SHORT,
    'Work Center ' || OBJID as STEXT,
    'WC' || LPAD(UNIFORM(1, 50, RANDOM()), 4, '0') as ARBPL,
    'PL' || LPAD(UNIFORM(1, 99, RANDOM()), 2, '0') as WERKS,
    'EM' || LPAD(UNIFORM(1, 10, RANDOM()), 2, '0') as BUKRS,
    'CC' || LPAD(UNIFORM(1, 100, RANDOM()), 5, '0') as KOSTL,
    CASE UNIFORM(1, 3, RANDOM()) 
        WHEN 1 THEN 'M' WHEN 2 THEN 'L' ELSE 'A' END as VERWE,
    'C' || LPAD(UNIFORM(1, 50, RANDOM()), 3, '0') as KAPID,
    CASE OTYPE 
        WHEN 'W' THEN '001' WHEN 'M' THEN '002' ELSE '003' END as KAPAR,
    UNIFORM(160, 720, RANDOM()) * 1.0 as KAPV1,
    'HR' as KAPE1,
    KAPV1 * UNIFORM(0.6, 1.1, RANDOM()) as KAPV2,
    KAPV1 * UNIFORM(0.7, 1.0, RANDOM()) as KAPV3,
    (KAPV2 / KAPV1) * 100 as AUSCH,
    CASE WHEN AUSCH > 100 THEN AUSCH - 100 ELSE 0 END as OVERL,
    'E' as SPRAS,
    SHORT as SORTF,
    'S' || LPAD(UNIFORM(1, 10, RANDOM()), 3, '0') as SCHGR,
    LPAD(UNIFORM(1, 5, RANDOM()), 2, '0') as TSTRAT,
    UNIFORM(0, 30, RANDOM()) as OFFSET,
    'MIN' as OFFSET_UNIT,
    KAPV1 * 2 as PROD_CAPACITY,
    'EA' as PROD_UNIT,
    UNIFORM(15, 120, RANDOM()) as SETUP_TIME,
    UNIFORM(30, 300, RANDOM()) as MACHINE_TIME,
    UNIFORM(15, 180, RANDOM()) as LABOR_TIME,
    UNIFORM(5, 60, RANDOM()) as QUEUE_TIME,
    UNIFORM(5, 45, RANDOM()) as WAIT_TIME,
    UNIFORM(10, 120, RANDOM()) as MOVE_TIME,
    UNIFORM(85, 98, RANDOM()) as EFFICIENCY,
    UNIFORM(92, 99, RANDOM()) as QUALITY_RATE,
    UNIFORM(90, 98, RANDOM()) as AVAILABILITY,
    (EFFICIENCY * QUALITY_RATE * AVAILABILITY) / 10000 as OEE
FROM TABLE(GENERATOR(ROWCOUNT => 400));

-- ENTERPRISE_PLANNING Tables
-- 0BWPLAN: 600 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.ENTERPRISE_PLANNING.OBWPLAN
SELECT 
    'PLAN' || LPAD(ROW_NUMBER() OVER (ORDER BY SEQ4()), 8, '0') as PLANNING_ID,
    LPAD(UNIFORM(1, 5, RANDOM()), 2, '0') as VERSION,
    '2024' as FISCYEAR,
    LPAD(UNIFORM(1, 12, RANDOM()), 2, '0') as FISCPERIOD,
    CASE UNIFORM(1, 2, RANDOM()) WHEN 1 THEN 'CA' ELSE 'OP' END as BUDGET_TYPE,
    CASE BUDGET_TYPE
        WHEN 'CA' THEN 
            CASE UNIFORM(1, 4, RANDOM())
                WHEN 1 THEN 'EQPT' WHEN 2 THEN 'FACL' 
                WHEN 3 THEN 'LAND' ELSE 'IT' END
        ELSE 
            CASE UNIFORM(1, 4, RANDOM())
                WHEN 1 THEN 'LABOR' WHEN 2 THEN 'SUPPL' 
                WHEN 3 THEN 'MKTG' ELSE 'ADMIN' END
    END as BUDGET_CATEGORY,
    'Budget for ' || BUDGET_CATEGORY || ' - ' || FISCPERIOD as BUDGET_DESC,
    CASE BUDGET_TYPE
        WHEN 'CA' THEN UNIFORM(100000, 5000000, RANDOM())
        ELSE UNIFORM(5000, 500000, RANDOM())
    END as PLAN_AMOUNT,
    PLAN_AMOUNT * UNIFORM(0.7, 1.1, RANDOM()) as ACTUAL_AMOUNT,
    PLAN_AMOUNT * UNIFORM(0.3, 0.9, RANDOM()) as COMMITTED_AMOUNT,
    PLAN_AMOUNT - COMMITTED_AMOUNT as REMAINING_AMOUNT,
    'USD' as CURRENCY,
    CASE BUDGET_TYPE
        WHEN 'CA' THEN 
            CASE UNIFORM(1, 4, RANDOM())
                WHEN 1 THEN 'MACH' WHEN 2 THEN 'BUIL' 
                WHEN 3 THEN 'PROP' ELSE 'SOFT' END
        ELSE NULL
    END as CAPEX_CATEGORY,
    CASE WHEN BUDGET_TYPE = 'CA' THEN 'PROJ' || LPAD(UNIFORM(1, 100, RANDOM()), 5, '0') ELSE NULL END as PROJECT_ID,
    CASE WHEN BUDGET_TYPE = 'CA' THEN 'AS' || LPAD(UNIFORM(1, 50, RANDOM()), 6, '0') ELSE NULL END as ASSET_CLASS,
    CASE CAPEX_CATEGORY
        WHEN 'MACH' THEN 'REPL'
        WHEN 'BUIL' THEN 'EXPN'
        WHEN 'PROP' THEN 'ACQR'
        ELSE 'DEVL'
    END as INVESTMENT_TYPE,
    '2023' as REQUEST_YEAR,
    '2024' as APPROVAL_YEAR,
    DATEADD(day, UNIFORM(0, 90, RANDOM()), CURRENT_DATE) as START_DATE,
    DATEADD(day, UNIFORM(180, 730, RANDOM()), START_DATE) as END_DATE,
    DATEADD(day, UNIFORM(0, 60, RANDOM()), START_DATE) as PAYMENT_DATE,
    UNIFORM(5, 25, RANDOM()) as EXPECTED_ROI,
    UNIFORM(2, 8, RANDOM()) as PAYBACK_PERIOD,
    PLAN_AMOUNT * UNIFORM(0.1, 0.5, RANDOM()) as NPV,
    UNIFORM(8, 20, RANDOM()) as IRR,
    CASE UNIFORM(1, 4, RANDOM())
        WHEN 1 THEN 'P' WHEN 2 THEN 'A' 
        WHEN 3 THEN 'R' ELSE 'C' END as STATUS,
    LPAD(UNIFORM(1, 5, RANDOM()), 1, '0') as PRIORITY,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 70 THEN 'AP' ELSE 'PD' END as APPROVAL_STATUS,
    CASE WHEN APPROVAL_STATUS = 'AP' THEN 'MGR' || LPAD(UNIFORM(1, 20, RANDOM()), 3, '0') ELSE NULL END as APPROVED_BY,
    CASE WHEN APPROVED_BY IS NOT NULL THEN DATEADD(day, -UNIFORM(0, 30, RANDOM()), CURRENT_DATE) ELSE NULL END as APPROVED_DATE,
    'CC' || LPAD(UNIFORM(1, 100, RANDOM()), 5, '0') as COST_CENTER,
    'PC' || LPAD(UNIFORM(1, 50, RANDOM()), 5, '0') as PROFIT_CENTER,
    'DEPT' || LPAD(UNIFORM(1, 20, RANDOM()), 3, '0') as DEPARTMENT,
    'D' || LPAD(UNIFORM(1, 10, RANDOM()), 3, '0') as DIVISION
FROM TABLE(GENERATOR(ROWCOUNT => 600));

-- MSDP: 1000 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.ENTERPRISE_PLANNING.MSDP
SELECT 
    'MAT' || LPAD(UNIFORM(1000, 9999, RANDOM()), 14, '0') as MATNR,
    'PL' || LPAD(UNIFORM(1, 99, RANDOM()), 2, '0') as WERKS,
    '001' as VERSION,
    DATEADD(day, UNIFORM(-30, 30, RANDOM()), DATE_TRUNC('MONTH', CURRENT_DATE)) as PERIOD_START,
    LAST_DAY(PERIOD_START) as PERIOD_END,
    CASE UNIFORM(1, 3, RANDOM()) 
        WHEN 1 THEN 'FC' WHEN 2 THEN 'SD' ELSE 'BK' END as DEMAND_CATEGORY,
    CASE UNIFORM(1, 4, RANDOM()) 
        WHEN 1 THEN 'RG' WHEN 2 THEN 'PR' 
        WHEN 3 THEN 'NW' ELSE 'SE' END as DEMAND_TYPE,
    CASE UNIFORM(1, 5, RANDOM()) 
        WHEN 1 THEN 'ES' WHEN 2 THEN 'HW' 
        WHEN 3 THEN 'SM' WHEN 4 THEN 'AR' ELSE 'WN' END as FORECAST_MODEL,
    UNIFORM(100, 10000, RANDOM()) * 1.0 as FORECAST_QTY,
    FORECAST_QTY * UNIFORM(0.8, 1.2, RANDOM()) as ACTUAL_DEMAND_QTY,
    FORECAST_QTY * 0.9 as BASELINE_FORECAST,
    CASE WHEN DEMAND_TYPE = 'PR' THEN FORECAST_QTY * 0.2 ELSE 0 END as PROMOTION_FORECAST,
    UNIFORM(0.7, 1.3, RANDOM()) as SEASONAL_FACTOR,
    UNIFORM(0.95, 1.05, RANDOM()) as TREND_FACTOR,
    'EA' as BASE_UOM,
    'EA' as SALES_UOM,
    ABS(FORECAST_QTY - ACTUAL_DEMAND_QTY) as MEAN_ABSOLUTE_ERROR,
    (MEAN_ABSOLUTE_ERROR / NULLIF(ACTUAL_DEMAND_QTY, 0)) * 100 as MEAN_ABSOLUTE_PERCENT_ERROR,
    FORECAST_QTY - ACTUAL_DEMAND_QTY as BIAS,
    FORECAST_QTY * 0.1 as STANDARD_DEVIATION,
    FORECAST_QTY - (1.96 * STANDARD_DEVIATION) as CONFIDENCE_INTERVAL_LOWER,
    FORECAST_QTY + (1.96 * STANDARD_DEVIATION) as CONFIDENCE_INTERVAL_UPPER,
    UNIFORM(0.1, 0.5, RANDOM()) as ALPHA,
    UNIFORM(0.05, 0.3, RANDOM()) as BETA,
    UNIFORM(0.1, 0.4, RANDOM()) as GAMMA,
    CASE 
        WHEN MEAN_ABSOLUTE_PERCENT_ERROR < 10 THEN 'A'
        WHEN MEAN_ABSOLUTE_PERCENT_ERROR < 20 THEN 'B'
        ELSE 'C'
    END as MODEL_QUALITY,
    FORECAST_QTY * UNIFORM(1.0, 1.5, RANDOM()) as CAPACITY_CONSTRAINT,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 90 THEN 'N' ELSE 'Y' END as MATERIAL_CONSTRAINT,
    CASE WHEN UNIFORM(1, 100, RANDOM()) <= 85 THEN 'N' ELSE 'Y' END as SUPPLIER_CONSTRAINT,
    DATEADD(day, -UNIFORM(0, 60, RANDOM()), PERIOD_START) as CREATED_DATE,
    DATEADD(day, UNIFORM(0, 30, RANDOM()), CREATED_DATE) as LAST_UPDATED,
    CASE UNIFORM(1, 3, RANDOM()) WHEN 1 THEN 'S' WHEN 2 THEN 'M' ELSE 'L' END as FORECAST_HORIZON
FROM TABLE(GENERATOR(ROWCOUNT => 1000));

-- FINANCE_SYSTEMS Tables
-- FBL1N: 800 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.FINANCE_SYSTEMS.FBL1N
SELECT 
    'CUS' || LPAD(UNIFORM(1, 200, RANDOM()), 7, '0') as KUNNR,
    'EM' || LPAD(UNIFORM(1, 10, RANDOM()), 2, '0') as BUKRS,
    'DOC' || LPAD(ROW_NUMBER() OVER (ORDER BY SEQ4()), 7, '0') as BELNR,
    '2024' as GJAHR,
    LPAD(UNIFORM(1, 999, RANDOM()), 3, '0') as BUZEI,
    'Customer ' || KUNNR as NAME1,
    CASE UNIFORM(1, 5, RANDOM()) 
        WHEN 1 THEN 'US' WHEN 2 THEN 'CA' 
        WHEN 3 THEN 'MX' WHEN 4 THEN 'BR' ELSE 'UK' END as LAND1,
    CASE LAND1 
        WHEN 'US' THEN 
            CASE UNIFORM(1, 5, RANDOM()) 
                WHEN 1 THEN 'NY' WHEN 2 THEN 'CA' 
                WHEN 3 THEN 'TX' WHEN 4 THEN 'FL' ELSE 'IL' END
        ELSE '00' END as REGIO,
    'S' || LPAD(UNIFORM(1, 200, RANDOM()), 9, '0') as SORTL,
    CASE UNIFORM(1, 5, RANDOM()) 
        WHEN 1 THEN 'RV' WHEN 2 THEN 'RE' 
        WHEN 3 THEN 'KG' WHEN 4 THEN 'DZ' ELSE 'AB' END as BLART,
    DATEADD(day, -UNIFORM(0, 180, RANDOM()), CURRENT_DATE) as BLDAT,
    DATEADD(day, -UNIFORM(0, 30, RANDOM()), BLDAT) as BUDAT,
    BLDAT as ZFBDT,
    CASE UNIFORM(1, 4, RANDOM()) 
        WHEN 1 THEN '0001' WHEN 2 THEN '0002' 
        WHEN 3 THEN '0003' ELSE '0004' END as ZTERM,
    CASE UNIFORM(1, 4, RANDOM()) 
        WHEN 1 THEN 'C' WHEN 2 THEN 'B' 
        WHEN 3 THEN 'K' ELSE 'S' END as ZLSCH,
    UNIFORM(1000, 50000, RANDOM()) * 1.0 as DMBTR,
    'USD' as WAERS,
    DMBTR as WRBTR,
    DMBTR * CASE ZTERM 
        WHEN '0001' THEN 0.02
        WHEN '0002' THEN 0.01
        ELSE 0 END as SKNTO,
    DATEADD(day, CASE ZTERM 
        WHEN '0001' THEN 30
        WHEN '0002' THEN 45
        WHEN '0003' THEN 60
        ELSE 90 END, BLDAT) as NETDT,
    DMBTR as SKFBT,
    DATEDIFF(day, NETDT, CURRENT_DATE) as DAYS_OVERDUE,
    CASE 
        WHEN DAYS_OVERDUE <= 0 THEN 'A'
        WHEN DAYS_OVERDUE <= 30 THEN 'B'
        WHEN DAYS_OVERDUE <= 60 THEN 'C'
        ELSE 'D'
    END as AGING_CATEGORY,
    CASE WHEN DAYS_OVERDUE > 60 THEN '2' WHEN DAYS_OVERDUE > 30 THEN '1' ELSE '0' END as DUNN_LEVEL,
    '' as MANSP,
    CASE WHEN DAYS_OVERDUE > 0 THEN DATEADD(day, -DAYS_OVERDUE, CURRENT_DATE) ELSE NULL END as MADAT,
    CASE WHEN DAYS_OVERDUE <= 0 THEN CURRENT_DATE ELSE NULL END as AUGDT,
    CASE WHEN AUGDT IS NOT NULL THEN 'CL' || LPAD(UNIFORM(1, 9999999, RANDOM()), 8, '0') ELSE NULL END as AUGBL,
    'PO-' || LPAD(UNIFORM(1000, 9999, RANDOM()), 8, '0') as ZUONR,
    'REF' || BELNR as XBLNR,
    CASE WHEN DMBTR > 0 THEN 'S' ELSE 'H' END as SHKZG,
    CASE WHEN AUGDT IS NULL THEN 'X' ELSE '' END as OPEN_ITEM,
    '' as UMSKZ
FROM TABLE(GENERATOR(ROWCOUNT => 800));

-- FDMDELTA: 400 records
INSERT INTO SAP_BDC_HORIZON_CATALOG.FINANCE_SYSTEMS.FDMDELTA
WITH forecast_periods AS (
    SELECT 
        'CF' || LPAD(ROW_NUMBER() OVER (ORDER BY SEQ4()), 8, '0') as CASH_ID,
        'EM' || LPAD(UNIFORM(1, 10, RANDOM()), 2, '0') as COMPANY_CODE,
        '2024' as FISCAL_YEAR,
        LPAD(UNIFORM(1, 12, RANDOM()), 2, '0') as PERIOD,
        UNIFORM(1, 3, RANDOM()) as FORECAST_TYPE,
        DATE_TRUNC('MONTH', DATEADD(month, UNIFORM(0, 3, RANDOM()), CURRENT_DATE)) as FORECAST_DATE
    FROM TABLE(GENERATOR(ROWCOUNT => 400))
)
SELECT 
    CASH_ID,
    COMPANY_CODE,
    FISCAL_YEAR,
    PERIOD,
    CASE FORECAST_TYPE
        WHEN 1 THEN 'ST'
        WHEN 2 THEN 'MD'
        ELSE 'LG'
    END as FORECAST_TYPE,
    FORECAST_DATE,
    CASE FORECAST_TYPE
        WHEN 1 THEN 30
        WHEN 2 THEN 90
        ELSE 180
    END as HORIZON_DAYS,
    -- Inflows
    UNIFORM(100000, 1000000, RANDOM()) as RECEIVABLES_INFLOW,
    UNIFORM(50000, 500000, RANDOM()) as SALES_INFLOW,
    UNIFORM(10000, 100000, RANDOM()) as OTHER_INFLOW,
    RECEIVABLES_INFLOW + SALES_INFLOW + OTHER_INFLOW as TOTAL_INFLOW,
    -- Outflows
    UNIFORM(50000, 500000, RANDOM()) as PAYABLES_OUTFLOW,
    UNIFORM(100000, 400000, RANDOM()) as PAYROLL_OUTFLOW,
    UNIFORM(20000, 150000, RANDOM()) as TAX_OUTFLOW,
    UNIFORM(30000, 300000, RANDOM()) as CAPEX_OUTFLOW,
    UNIFORM(10000, 100000, RANDOM()) as OTHER_OUTFLOW,
    PAYABLES_OUTFLOW + PAYROLL_OUTFLOW + TAX_OUTFLOW + CAPEX_OUTFLOW + OTHER_OUTFLOW as TOTAL_OUTFLOW,
    TOTAL_INFLOW - TOTAL_OUTFLOW as NET_CASH_FLOW,
    UNIFORM(200000, 500000, RANDOM()) as OPENING_BALANCE,
    OPENING_BALANCE + NET_CASH_FLOW as CLOSING_BALANCE,
    100000 as MINIMUM_BALANCE,
    CLOSING_BALANCE - MINIMUM_BALANCE as EXCESS_DEFICIT,
    'USD' as CURRENCY,
    CASE FORECAST_TYPE
        WHEN 1 THEN UNIFORM(85, 98, RANDOM())
        WHEN 2 THEN UNIFORM(75, 90, RANDOM())
        ELSE UNIFORM(60, 80, RANDOM())
    END as CONFIDENCE_LEVEL,
    (100 - CONFIDENCE_LEVEL) as VARIANCE_PERCENT,
    -- Liquidity Ratios
    UNIFORM(1.2, 2.5, RANDOM()) as CURRENT_RATIO,
    UNIFORM(0.8, 1.8, RANDOM()) as QUICK_RATIO,
    UNIFORM(30, 60, RANDOM()) as DAYS_SALES_OUTSTANDING,
    UNIFORM(25, 55, RANDOM()) as DAYS_PAYABLE_OUTSTANDING,
    'SAP_ERP' as DATA_SOURCE,
    CURRENT_TIMESTAMP as LAST_REFRESH
FROM forecast_periods;

-- Verify record counts for all tables
SELECT 'S4HANA_ALL_REGIONS.MATDOC' as table_name, COUNT(*) as record_count 
FROM SAP_BDC_HORIZON_CATALOG.S4HANA_ALL_REGIONS.MATDOC
UNION ALL
SELECT 'S4HANA_ALL_REGIONS.ME2N', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.S4HANA_ALL_REGIONS.ME2N
UNION ALL
SELECT 'S4HANA_ALL_REGIONS.MARC', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.S4HANA_ALL_REGIONS.MARC
UNION ALL
SELECT 'S4HANA_ALL_REGIONS.MD04', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.S4HANA_ALL_REGIONS.MD04
UNION ALL
SELECT 'S4HANA_APAC.VBAK', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.S4HANA_APAC.VBAK
UNION ALL
SELECT 'S4HANA_APAC.VBAP', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.S4HANA_APAC.VBAP
UNION ALL
SELECT 'S4HANA_APAC.LIKP', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.S4HANA_APAC.LIKP
UNION ALL
SELECT 'S4HANA_APAC.LIPS', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.S4HANA_APAC.LIPS
UNION ALL
SELECT 'S4HANA_APAC.KONV', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.S4HANA_APAC.KONV
UNION ALL
SELECT 'S4HANA_EMEA.ACDOCA', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.S4HANA_EMEA.ACDOCA
UNION ALL
SELECT 'S4HANA_EMEA.FAGLFLEXA', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.S4HANA_EMEA.FAGLFLEXA
UNION ALL
SELECT 'ECC_AMERICAS.PA0007', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.ECC_AMERICAS.PA0007
UNION ALL
SELECT 'ECC_AMERICAS.PA0008', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.ECC_AMERICAS.PA0008
UNION ALL
SELECT 'ECC_AMERICAS.PP01', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.ECC_AMERICAS.PP01
UNION ALL
SELECT 'ENTERPRISE_PLANNING.0BWPLAN', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.ENTERPRISE_PLANNING.OBWPLAN
UNION ALL
SELECT 'ENTERPRISE_PLANNING.MSDP', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.ENTERPRISE_PLANNING.MSDP
UNION ALL
SELECT 'FINANCE_SYSTEMS.FBL1N', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.FINANCE_SYSTEMS.FBL1N
UNION ALL
SELECT 'FINANCE_SYSTEMS.FDMDELTA', COUNT(*) 
FROM SAP_BDC_HORIZON_CATALOG.FINANCE_SYSTEMS.FDMDELTA
ORDER BY table_name;



-- 18+ tables across all required schemas
-- 500-2000 records per table (total ~15,000+ records)
-- Realistic SAP field structures with proper data types
-- Business-relevant relationships between tables
-- Time-series data for trend analysis
-- Multi-region distribution (APAC, EMEA, Americas)
-- Complete referential integrity where needed

