USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SAP_COMPUTE;
USE DATABASE SAP_BDC_HORIZON_CATALOG;
USE SCHEMA AGENTS;


-- grant user to have access to secuirty scanner
/*
CREATE ROLE TC_ADMIN_ROLE; 
GRANT APPLICATION ROLE SNOWFLAKE.TRUST_CENTER_ADMIN TO ROLE TC_ADMIN_ROLE;
SET my_user = CURRENT_USER();
GRANT ROLE TC_ADMIN_ROLE TO USER IDENTIFIER($my_user);
USE ROLE TC_ADMIN_ROLE;

SELECT * FROM snowflake.trust_center.findings;
*/



-- REFRESH_INVENTORY_DEMAND_PATTERNS
ALTER TASK REFRESH_INVENTORY_DEMAND_PATTERNS SUSPEND; -- suspend

-- INVENTORY_DEMAND_SEARCH
-- both index and serving
ALTER CORTEX SEARCH SERVICE INVENTORY_DEMAND_SEARCH SUSPEND;

ALTER CORTEX SEARCH SERVICE INVENTORY_DEMAND_SEARCH SUSPEND INDEXING;
-- or
ALTER CORTEX SEARCH SERVICE INVENTORY_DEMAND_SEARCH SUSPEND SERVING;


-- See all active dynamic tables and their refresh intervals
SHOW DYNAMIC TABLES;
-- See all scheduled tasks
SHOW TASKS IN ACCOUNT;
-- See Cortex Search services
SHOW CORTEX SEARCH SERVICES IN ACCOUNT;




/* Cost measures */

-- sheet 1 
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY
WHERE USAGE_DATE >= '2026-03-25' -- AND USAGE_DATE < '2026-03-23'
ORDER BY USAGE_DATE DESC;

Select * FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
where START_TIME > '2026-03-21' AND START_TIME < '2026-03-23'
ORDER BY START_TIME;

-- with time sheet 3
SELECT SERVICE_TYPE, ENTITY_TYPE, NAME,DATABASE_NAME, START_TIME,END_TIME,datediff('MINUTE',START_TIME,END_TIME) as TOTAL_TIME,  sum(CREDITS_USED_COMPUTE), sum(CREDITS_USED_CLOUD_SERVICES),sum(CREDITS_USED) FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
where START_TIME > '2026-03-24' AND START_TIME < '2026-03-26'
group by SERVICE_TYPE, ENTITY_TYPE, NAME,DATABASE_NAME,START_TIME,END_TIME,TOTAL_TIME
ORDER BY START_TIME ;

-- no time sheet 2
SELECT SERVICE_TYPE, ENTITY_TYPE, NAME,DATABASE_NAME,  sum(CREDITS_USED_COMPUTE), sum(CREDITS_USED_CLOUD_SERVICES),sum(CREDITS_USED) FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
group by SERVICE_TYPE, ENTITY_TYPE, NAME,DATABASE_NAME
order by ENTITY_TYPE,NAME, DATABASE_NAME;

SELECT * FROM snowflake.account_usage.CORTEX_FUNCTIONS_QUERY_USAGE_HISTORY;

SELECT * FROM snowflake.account_usage.CORTEX_CODE_CLI_USAGE_HISTORY;

SELECT * FROM snowflake.account_usage.CORTEX_SEARCH_SERVING_USAGE_HISTORY;
SELECT * FROM snowflake.account_usage.CORTEX_SEARCH_BATCH_QUERY_USAGE_HISTORY;
SELECT * FROM snowflake.account_usage.CORTEX_SEARCH_SERVING_USAGE_HISTORY;


SELECT * FROM SNOWFLAKE.account_usage.storage_usage;
-- storage by table and database, schema
SELECT 
    TABLE_CATALOG AS DATABASE_NAME,
    TABLE_SCHEMA AS SCHEMA_NAME,
    TABLE_NAME,
    ROUND(ACTIVE_BYTES / (1024*1024), 2) AS ACTIVE_STORAGE_MB,
    ROUND(TIME_TRAVEL_BYTES / (1024*1024), 2) AS TIME_TRAVEL_STORAGE_MB,
    ROUND(FAILSAFE_BYTES / (1024*1024), 2) AS FAILSAFE_STORAGE_MB,
    ROUND(RETAINED_FOR_CLONE_BYTES / (1024*1024), 2) AS RETAINED_FOR_CLONE_MB,
    (ACTIVE_STORAGE_MB + TIME_TRAVEL_STORAGE_MB+ FAILSAFE_STORAGE_MB + RETAINED_FOR_CLONE_MB) AS TOTAL_STORAGE_MB
FROM 
    SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
WHERE DATABASE_NAME <> 'SNOWFLAKE'
ORDER BY 
    TOTAL_STORAGE_MB DESC;

-- expensive queries
SELECT
    QUERY_ID,
    QUERY_TEXT,
    USER_NAME,
    WAREHOUSE_NAME,
    START_TIME,
    END_TIME,
    TOTAL_ELAPSED_TIME / 1000 AS EXECUTION_TIME_SECONDS,
    -- Estimated cost calculation: credits per hour * hours executed
    -- This assumes standard Snowflake pricing tiers for simplicity
    (CASE
        WHEN WAREHOUSE_SIZE = 'X-Small' THEN 1
        WHEN WAREHOUSE_SIZE = 'Small' THEN 2
        WHEN WAREHOUSE_SIZE = 'Medium' THEN 4
        WHEN WAREHOUSE_SIZE = 'Large' THEN 8
        WHEN WAREHOUSE_SIZE = 'X-Large' THEN 16
        WHEN WAREHOUSE_SIZE = '2X-Large' THEN 32
        WHEN WAREHOUSE_SIZE = '3X-Large' THEN 64
        WHEN WAREHOUSE_SIZE = '4X-Large' THEN 128
    END) * (TOTAL_ELAPSED_TIME / 1000.0 / 3600.0) AS ESTIMATED_CREDITS_CONSUMED
FROM
    SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE
    START_TIME >= DATEADD(day, -1, CURRENT_TIMESTAMP()) -- Filter for the last 7 days
    AND ERROR_CODE IS NULL -- Exclude failed queries
ORDER BY
    ESTIMATED_CREDITS_CONSUMED DESC
LIMIT 10;



SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS;

-- Set the session timezone to UTC for consistency
ALTER SESSION SET TIMEZONE = 'UTC';

-- Query to combine current table sizes with daily database storage increases
WITH DailyDatabaseGrowth AS (
    SELECT
        USAGE_DATE,
        DATABASE_NAME,
        -- Calculate daily increase in storage bytes
        AVERAGE_DATABASE_BYTES - LAG(AVERAGE_DATABASE_BYTES, 1, AVERAGE_DATABASE_BYTES) OVER (
            PARTITION BY DATABASE_NAME
            ORDER BY USAGE_DATE
        ) AS DAILY_INCREASE_BYTES
    FROM
        SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
    WHERE
        USAGE_DATE >= CURRENT_DATE() - INTERVAL '30 days' -- Adjust the date range as needed (max 1 year history)
),
CurrentTableSizes AS (
    SELECT
        TABLE_CATALOG AS DATABASE_NAME,
        TABLE_SCHEMA,
        TABLE_NAME,
        -- Combine active and time travel bytes for total current size
        (ACTIVE_BYTES + TIME_TRAVEL_BYTES + FAILSAFE_BYTES) AS TOTAL_BYTES
    FROM
        SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
    WHERE
        DELETED IS NULL -- Filter out dropped tables not in failsafe
)
SELECT
    DDG.USAGE_DATE,
    CTS.DATABASE_NAME,
    CTS.TABLE_SCHEMA,
    CTS.TABLE_NAME,
    CTS.TOTAL_BYTES AS CURRENT_SIZE_BYTES,
    DDG.DAILY_INCREASE_BYTES -- This is the total database daily increase, not specific to the table
FROM
    CurrentTableSizes CTS
JOIN
    DailyDatabaseGrowth DDG ON CTS.DATABASE_NAME = DDG.DATABASE_NAME
ORDER BY
    DDG.USAGE_DATE DESC,
    CTS.DATABASE_NAME,
    CTS.TABLE_SCHEMA,
    CTS.TABLE_NAME;
    
DESCRIBE TABLE SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY;

select * from SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY where database_name <> 'SNOWFLAKE';
select * from SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS where TABLE_CATALOG <> 'SNOWFLAKE';

/*
 • CORTEX_AGENT_USAGE_HISTORY
 • CORTEX_AISQL_USAGE_HISTORY
 • CORTEX_AI_FUNCTIONS_USAGE_HISTORY
 • CORTEX_ANALYST_USAGE_HISTORY
 • CORTEX_CODE_CLI_USAGE_HISTORY
 • CORTEX_DOCUMENT_PROCESSING_USAGE_HISTORY
 • CORTEX_FINE_TUNING_USAGE_HISTORY
 • CORTEX_FUNCTIONS_QUERY_USAGE_HISTORY
 • CORTEX_FUNCTIONS_USAGE_HISTORY
 • CORTEX_PROVISIONED_THROUGHPUT_USAGE_HISTORY
 • CORTEX_REST_API_USAGE_HISTORY
 • CORTEX_SEARCH_BATCH_QUERY_USAGE_HISTORY
 • CORTEX_SEARCH_DAILY_USAGE_HISTORY
 • CORTEX_SEARCH_SERVING_USAGE_HISTORY
 */

/*
Step 2: Create a Network Rule
Using a Snowflake role with the CREATE NETWORK RULE privilege (e.g., ACCOUNTADMIN or SECURITYADMIN), run the following SQL commands to create a network rule in your desired schema: 
Snowflake Docs

Replace '<your_ip_address/CIDR>' with the actual IP you identified.
sql
USE ROLE SECURITYADMIN;
CREATE NETWORK RULE IF NOT EXISTS allow_my_office_ip
  TYPE = IPV4
  MODE = INGRESS
  VALUE_LIST = ('<your_ip_address/CIDR>')
  COMMENT = 'Allows access from my specific IP address';
 
Snowflake Docs
Step 3: Create a Network Policy
Next, create the network policy and associate the network rule you just created with its allowed list: 
Medium

sql
CREATE NETWORK POLICY allow_access_policy
  ALLOWED_NETWORK_RULE_LIST = ('allow_my_office_ip')
  COMMENT = 'Policy to allow specific network access';
 
Step 4: Activate the Network Policy
You have two options for activation:
User-level (Recommended for testing): Apply the policy only to the specific user experiencing the issue. User-level policies take precedence over account-level policies.
sql
ALTER USER <username> SET NETWORK_POLICY = allow_access_policy;
Account-level: Apply the policy to the entire Snowflake account.
sql
ALTER ACCOUNT SET NETWORK_POLICY = allow_access_policy;
*/

USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE SAP_BDC_HORIZON_CATALOG TO ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA SAP_BDC_HORIZON_CATALOG.AGENTS TO ROLE SECURITYADMIN;
CREATE NETWORK RULE IF NOT EXISTS allow_my_office_ip
  TYPE = IPV4
  MODE = INGRESS
  VALUE_LIST = ('x.x.x.x/24')
  COMMENT = 'Allows access from my specific IP address';

CREATE NETWORK POLICY allow_access_policy
  ALLOWED_NETWORK_RULE_LIST = ('allow_my_office_ip')
  COMMENT = 'Policy to allow specific network access';
ALTER ACCOUNT SET NETWORK_POLICY = allow_access_policy;
  